version: "3.3"
services:
  fauxauth:
    image: textbook/fauxauth:${TAG}
    environment:
      DEBUG: "fauxauth:*"
      PORT: 3210
  e2e:
    build:
      args:
        ALPINE_RELEASE: 3.16
        NODE_RELEASE: ${NODE_RELEASE}
      context: ../..
      dockerfile: ./packages/e2e/Dockerfile
    entrypoint: "sh"
    command:
      - "-c"
      - "npx wait-on --log --timeout 60000 http-get://selenium:4444/ && npm --workspace=packages/e2e test -- --testTimeout 60000"
    environment:
      BROWSER: firefox
      FAUXAUTH_URL: http://fauxauth:3210
      JEST_TIMEOUT: 60000
      SELENIUM_HOST: selenium
      SELENIUM_PATH: /
    image: textbook/fauxauth-e2e
    links:
      - fauxauth
      - selenium
  selenium:
    image: selenium/standalone-firefox:4
