sudo: required

language: node_js

cache:
  directories:
    - "node_modules"

services:
  - docker

before_script:
  # prettier-ignore
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run lint
  - npm run test:cover
  - npm run build
  - npm run e2e

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
  - provider: script
    script: bash deploy-docker.sh
    on:
      tags: true
  - provider: npm
    email: $NPM_EMAIL_ADDRESS
    api_key: $NPM_AUTH_TOKEN
    on:
      tags: true
