sudo: required

language: node_js

node_js:
  - 10

cache:
  directories:
    - "node_modules"

services:
  - docker

script:
  - npm run lint
  - npm run test:cover

deploy:
  - provider: script
    script: bash deploy-docker.sh
    on:
      tags: true
