version: "3.3"
services:
  fauxauth:
    build:
      context: .
      labels:
        - version=$TRAVIS_TAG
    image: textbook/fauxauth
  e2e:
    build:
      context: .
      dockerfile: tests/e2e/Dockerfile
    environment:
      - FAUXAUTH_URL=http://fauxauth
    links:
      - fauxauth
