sonar.organization=textbook
sonar.projectKey=textbook_fauxauth
sonar.projectName=fauxauth

sonar.javascript.lcov.reportPaths=./packages/fauxauth/coverage/lcov.info
sonar.coverage.exclusions=packages/fauxauth/jest.config.js,packages/fauxauth/**/*.spec.ts,packages/e2e/**
