---
name: "Test with coverage"

description: "Run tests and report coverage to CodeClimate"

inputs:
  reporter-id:
    description: "CodeClimate Test Reporter ID"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Set up CodeClimate reporter"
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build
      env:
        CC_TEST_REPORTER_ID: ${{ inputs.reporter-id }}
      shell: "bash"
    - run: "npm run test:cover"
      shell: "bash"
    - name: "Generate coverage report"
      run: "./cc-test-reporter format-coverage -t clover ./reports/coverage/clover.xml"
      shell: "bash"
    - name: "Report test outcomes"
      run: "./cc-test-reporter upload-coverage"
      env:
        CC_TEST_REPORTER_ID: ${{ inputs.reporter-id }}
      shell: "bash"
