---
name: "Test with coverage"

description: "Run tests and report coverage"

inputs:
  sonar-token:
    description: "Token for Sonar Cloud"
    required: true

runs:
  using: "composite"
  steps:
    - run: "npm run test:cover"
      shell: "bash"
      working-directory: "packages/fauxauth"
    - uses: "SonarSource/sonarqube-scan-action@v7"
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
