version: 2

node: &node
  docker:
    - image: circleci/node:10.16.3

all_builds: &all_builds
  filters:
    tags:
      only: /v\d+(\.\d+)*/

release_only: &release_only
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /v\d+(\.\d+)*/

e2e: &e2e
  steps:
    - checkout
    - attach_workspace:
        at: .
    - restore_cache:
        keys:
          - fauxauth-npm-{{ checksum "package-lock.json" }}
    - run:
        name: Info
        command: 'echo "Node: $(node -v)" && echo "NPM: v$(npm -v)"'
    - run:
        name: Install Fauxauth
        command: npm ci --only=prod || npm install --only=prod
    - run:
        name: Run Fauxauth
        command: npm start
        background: true
    - run:
        name: Install E2E
        command: npm ci --only=prod || npm install --only=prod
        working_directory: e2e
    - run:
        name: Test
        command: npm run test
        working_directory: e2e
        environment:
          JEST_JUNIT_OUTPUT_DIR: ./reports/jest
    - store_test_results:
        path: ./e2e/reports

jobs:
  dependencies:
    <<: *node
    steps:
      - checkout
      - restore_cache:
          keys:
            - fauxauth-npm-{{ checksum "package-lock.json" }}
      - run:
          name: Info
          command: 'echo "Node: $(node -v)" && echo "NPM: v$(npm -v)"'
      - run:
          name: Check Node
          command: |
            if [[ "$(node -v)" == "v$(cat .nvmrc)" ]]; \
            then echo 'Node version OK'; \
            else echo 'Node version mismatch' && exit 1; \
            fi
      - run:
          name: Install
          command: npm ci
      - save_cache:
          key: fauxauth-npm-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

  lint:
    <<: *node
    steps:
      - checkout
      - restore_cache:
          keys:
            - fauxauth-npm-{{ checksum "package-lock.json" }}
      - run:
          name: Install
          command: npm ci
      - run:
          name: Lint
          command: npm run lint

  test:
    <<: *node
    steps:
      - checkout
      - restore_cache:
          keys:
            - fauxauth-npm-{{ checksum "package-lock.json" }}
      - run:
          name: Install
          command: npm ci
      - run:
          name: Install CodeClimate Reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
      - run:
          name: Test
          command: npm run test:report
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/jest
      - run:
          name: Use CodeClimate Reporter
          command: ./cc-test-reporter after-build
      - store_test_results:
          path: ./reports

  build:
    <<: *node
    steps:
      - checkout
      - restore_cache:
          keys:
            - fauxauth-npm-{{ checksum "package-lock.json" }}
      - run:
          name: Install
          command: npm ci
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - ./lib

  e2e:
    <<: *node
    <<: *e2e

  e2e-dubnium:
    <<: *e2e
    docker:
      - image: circleci/node:10

  e2e-carbon:
    <<: *e2e
    docker:
      - image: circleci/node:8

  e2e-boron:
    <<: *e2e
    docker:
      - image: circleci/node:6

  deploy-docker:
    <<: *node
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          name: Deploy to Docker Hub
          command: ./deploy-docker.sh

  deploy-npm:
    <<: *node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Deploy to NPM
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > "$HOME/.npmrc"
            npm publish

  smoke-test:
    <<: *node
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install E2E
          command: npm ci
          working_directory: e2e
      - run:
          name: Smoke Test
          command: './smoke-test.sh "$CIRCLE_TAG"'
          working_directory: e2e

workflows:
  version: 2
  build_and_test:
    jobs:
      - dependencies:
          <<: *all_builds
      - lint:
          <<: *all_builds
          requires:
            - dependencies
      - test:
          <<: *all_builds
          requires:
            - dependencies
      - build:
          <<: *all_builds
          requires:
            - dependencies
      - e2e:
          <<: *all_builds
          requires:
            - build
      - e2e-dubnium:
          <<: *all_builds
          requires:
            - lint
            - test
            - e2e
      - e2e-carbon:
          <<: *all_builds
          requires:
            - lint
            - test
            - e2e
      - e2e-boron:
          <<: *all_builds
          requires:
            - lint
            - test
            - e2e
      - deploy-docker:
          <<: *release_only
          requires:
            - e2e-boron
            - e2e-carbon
            - e2e-dubnium
      - deploy-npm:
          <<: *release_only
          requires:
            - e2e-boron
            - e2e-carbon
            - e2e-dubnium
      - smoke-test:
          <<: *release_only
          requires:
            - deploy-docker
            - deploy-npm
