version: "3.3"
services:
  fauxauth:
    image: textbook/fauxauth:${TAG}
  e2e:
    build:
      args:
        - NODE_RELEASE=14.16.1
      context: .
    environment:
      - FAUXAUTH_URL=http://fauxauth
      - SELENIUM_HOST=selenium
    links:
      - fauxauth
      - selenium
  selenium:
    image: selenium/standalone-chrome
