version: "3.3"
services:
  fauxauth:
    image: textbook/fauxauth:${TAG}
    environment:
      DEBUG: "fauxauth:*"
      PORT: 3210
  e2e:
    build:
      args:
        ALPINE_RELEASE: 3.14
        NODE_RELEASE: 16.13.0
      context: .
    environment:
      FAUXAUTH_URL: http://fauxauth:3210
      SELENIUM_HOST: selenium
      SELENIUM_PATH: /
    links:
      - fauxauth
      - selenium
  selenium:
    image: selenium/standalone-chrome:4
