version: "3.3"
services:
  fauxauth:
    image: textbook/fauxauth:${TAG}
  e2e:
    build:
      args:
        ALPINE_RELEASE: 3.14
        NODE_RELEASE: 14.17.3
      context: .
    environment:
      FAUXAUTH_URL: http://fauxauth
      SELENIUM_HOST: selenium
    links:
      - fauxauth
      - selenium
  selenium:
    image: selenium/standalone-chrome
