---
name: "Run E2E tests in specified Node version"

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: "string"
      node-version:
        required: true
        type: "string"

jobs:
  e2e:
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Get Chrome version"
        id: "chrome"
        run: 'echo "version=$(google-chrome --version)" >> $GITHUB_OUTPUT'
      - name: "Check out repository"
        uses: "actions/checkout@v3"
      - name: "Retrieve build output"
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: "packages/fauxauth/lib"
      - name: "Set up Node environment"
        uses: "actions/setup-node@v3"
        with:
          cache: "npm"
          node-version: ${{ inputs.node-version }}
      - name: "Install NPM 8+ for workspace support"
        run: |
          if [[ "$(npm -v | cut -d. -f1)" -lt "8" ]]; then
            npm install --global npm@8
          fi
        shell: "bash"
      - name: "Install dependencies"
        env:
          CHROME_VERSION: ${{ steps.chrome.outputs.version }}
        run: |
          npm ci
          npm run install:chromedriver
      - name: "Run E2E tests"
        run: "npm run e2e"
        env:
          DEBUG: "fauxauth:*"
