---
name: "Node.js CI"

on:
  - "push"
  - "pull_request"

jobs:
  build:
    runs-on: "ubuntu-22.04"
    outputs:
      node-version: ${{ steps.node-version.outputs.node-version }}
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v3"
      - name: "Get Node version"
        run: 'echo "node-version=$(cat .nvmrc)" >> $GITHUB_OUTPUT'
        id: "node-version"
      - name: "Set up Node environment"
        uses: "actions/setup-node@v3"
        with:
          cache: "npm"
          node-version: ${{ steps.node-version.outputs.node-version }}
      - name: "Install dependencies"
        run: "npm ci"
      - name: "Check code style"
        run: "npm run lint"
      - name: "Run tests and report coverage"
        uses: "./.github/actions/test-coverage"
        with:
          reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}
  e2e:
    needs:
      - "build"
    strategy:
      matrix:
        node-version:
          - ${{ needs.build.outputs.node-version }}
          - "lts/fermium"
          - "lts/gallium"
          - "lts/hydrogen"
    uses: "./.github/workflows/e2e.yml"
    with:
      node-version: ${{ matrix.node-version }}
