---
name: "Node.js CI"

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: "ubuntu-latest"
    outputs:
      node-version: ${{ steps.node-version.outputs.node }}
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v6"
        with:
          fetch-depth: 0
      - name: "Node version"
        id: "node-version"
        run: |
          echo "node=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      - name: "Set up Node environment"
        uses: "actions/setup-node@v6"
        id: "setup-node"
        with:
          cache: "npm"
          node-version: ${{ steps.node-version.outputs.node }}
      - name: "Install dependencies"
        run: "npm ci"
      - name: "Check code style"
        run: "npm run lint"
      - name: "Run tests and report coverage"
        uses: "./.github/actions/test-coverage"
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
      - name: "Build package"
        run: |
          npm run build
          npm --workspace fauxauth pack
          mv fauxauth-*.tgz package.tgz
      - name: "Set up Docker BuildX"
        uses: "docker/setup-buildx-action@v4"
      - name: "Build Docker container"
        uses: "docker/build-push-action@v7"
        with:
          build-args: |
            ALPINE_RELEASE=3.23
            NODE_RELEASE=${{ steps.node-version.outputs.node }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          push: false
      - name: "Store build output"
        uses: "actions/upload-artifact@v7"
        with:
          if-no-files-found: "error"
          name: "fauxauth-lib"
          path: "packages/fauxauth/lib"
      - name: "Store package output"
        uses: "actions/upload-artifact@v7"
        with:
          if-no-files-found: "error"
          name: "fauxauth-pkg"
          path: "package.tgz"
  e2e:
    needs:
      - "build"
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - "22.12.0"
          - ${{ needs.build.outputs.node-version }}
          - "lts/jod"
          - "lts/krypton"
          - "latest"
    uses: "./.github/workflows/e2e.yml"
    with:
      artifact-name: "fauxauth-lib"
      continue-on-error: ${{ matrix.node-version == 'latest' }}
      node-version: ${{ matrix.node-version }}
  deploy-docker:
    needs:
      - "e2e"
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: "ubuntu-latest"
    environment:
      name: "docker"
      url: "https://hub.docker.com/r/textbook/fauxauth"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v6"
      - name: "Get metadata"
        id: metadata
        run: |
          echo "major="$(echo "$TAG" | cut -d. -f1)"" >> $GITHUB_OUTPUT
          echo "minor="$(echo "$TAG" | cut -d. -f2)"" >> $GITHUB_OUTPUT
          echo "node=$(cat .nvmrc)" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT
        env:
          TAG: ${{ github.ref_name }}
      - name: "Set up Docker BuildX"
        uses: "docker/setup-buildx-action@v4"
      - name: "Log in to Docker Hub"
        uses: "docker/login-action@v4"
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          username: ${{ vars.DOCKER_USERNAME }}
      - name: "Build and push container"
        uses: "docker/build-push-action@v7"
        with:
          build-args: |
            ALPINE_RELEASE=3.23
            NODE_RELEASE=${{ steps.metadata.outputs.node }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          labels: |
            version=${{ github.ref_name }}
          push: true
          sbom: true
          tags: |
            textbook/fauxauth
            textbook/fauxauth:${{ steps.metadata.outputs.major }}
            textbook/fauxauth:${{ steps.metadata.outputs.major }}.${{ steps.metadata.outputs.minor }}
            textbook/fauxauth:${{ steps.metadata.outputs.tag }}
      - name: "Update Docker Hub description"
        uses: "peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa"  # v5.0.0
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: "textbook/fauxauth"
          username: ${{ vars.DOCKER_USERNAME }}
  deploy-github:
    needs:
      - "e2e"
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: "ubuntu-latest"
    steps:
      - name: "Retrieve build output"
        uses: "actions/download-artifact@v8"
        with:
          name: "fauxauth-pkg"
      - name: "Publish to GitHub"
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create \
            '${{ github.ref_name }}' \
            --title '${{ github.ref_name }}' \
            "package.tgz#NPM package"
  deploy-npm:
    needs:
      - "e2e"
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: read
      id-token: write
    environment:
      name: "npm"
      url: "https://www.npmjs.com/package/fauxauth"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Retrieve build output"
        uses: "actions/download-artifact@v8"
        with:
          name: "fauxauth-pkg"
      - name: "Set up Node environment"
        uses: "actions/setup-node@v6"
        id: "setup-node"
        with:
          node-version: "lts/*"
      - name: "Publish to NPM"
        run: |
          npm install --global npm@latest
          npm publish --provenance package.tgz
  smoke-test:
    needs:
      - "deploy-docker"
      - "deploy-npm"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v6"
      - name: "Validate published artifacts"
        run: |
          ./bin/smoke-test.sh "${{ github.ref_name }}"
