---
name: "Node.js CI"

on:
  - "push"
  - "pull_request"

jobs:
  build:
    runs-on: "ubuntu-22.04"
    outputs:
      node-version: ${{ steps.setup-node.outputs.node-version }}
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v3"
      - name: "Set up Node environment"
        uses: "actions/setup-node@v3"
        id: "setup-node"
        with:
          cache: "npm"
          node-version-file: ".nvmrc"
      - name: "Install dependencies"
        run: "npm ci"
      - name: "Check code style"
        run: "npm run lint"
      - name: "Run tests and report coverage"
        uses: "./.github/actions/test-coverage"
        with:
          reporter-id: ${{ secrets.CC_TEST_REPORTER_ID }}
      - name: "Build package"
        run: "npm run build"
      - name: "Store build output"
        uses: "actions/upload-artifact@v3"
        with:
          if-no-files-found: "error"
          name: "fauxauth-lib"
          path: "packages/fauxauth/lib"
  e2e:
    needs:
      - "build"
    strategy:
      matrix:
        node-version:
          - ${{ needs.build.outputs.node-version }}
          - "lts/fermium"
          - "lts/gallium"
          - "lts/hydrogen"
    uses: "./.github/workflows/e2e.yml"
    with:
      artifact-name: "fauxauth-lib"
      node-version: ${{ matrix.node-version }}
